version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mixologist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mixologist
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mixologist
    ports:
      - "15432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mixologist-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mixologist
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db 