name: mixologist_flutter
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  http: ^1.2.0
  firebase_core: ^3.13.1
    # flutter_client_sse removed
  visibility_detector: ^0.4.0
  vibration: ^1.8.4
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^6.0.0
