name: mixologist_flutter
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  http: ^1.2.0 
    # flutter_client_sse removed

flutter:
  uses-material-design: true
