name: mixologist_flutter
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  http: ^1.2.0
  firebase_core: ^2.24.0
    # flutter_client_sse removed
  visibility_detector: ^0.4.0
  vibration: ^1.8.4
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  # Camera and inventory management dependencies
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  # AI Assistant voice interaction dependencies
  rive: ^0.12.4
  web_socket_channel: ^3.0.0
  flutter_audio_capture: ^1.1.11
  just_audio: ^0.9.36
  # Fuzzy search for cocktail name matching
  fuzzy: ^0.5.1
  liquid_progress_indicator: ^0.4.0
  flutter_animate: ^4.2.0
  particles_flutter: ^0.1.3
  flutter_riverpod: ^2.4.0


flutter:
  uses-material-design: true
  assets:
    - assets/rive/
    - assets/audio/
    - assets/animations/placeholder.riv

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
