// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOsNH_IUFfMY7PC_K2B7YE2Vzj-WkGZwc',
    appId: '1:226125512359:web:2e2ccc12a9339d17cea582',
    messagingSenderId: '226125512359',
    projectId: 'mixologist-76592',
    authDomain: 'mixologist-76592.firebaseapp.com',
    storageBucket: 'mixologist-76592.firebasestorage.app',
    measurementId: 'G-Z9BD62JYCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-LvoxyQT0mf_2VevBGkzUHCncQ2b4E30',
    appId: '1:226125512359:android:4d26a000df4a4276cea582',
    messagingSenderId: '226125512359',
    projectId: 'mixologist-76592',
    storageBucket: 'mixologist-76592.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuDtcXDz7paw_87z63wymluYAFKO6yhos',
    appId: '1:226125512359:ios:131e31be576fd2eecea582',
    messagingSenderId: '226125512359',
    projectId: 'mixologist-76592',
    storageBucket: 'mixologist-76592.firebasestorage.app',
    iosBundleId: 'com.example.mixologistFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuDtcXDz7paw_87z63wymluYAFKO6yhos',
    appId: '1:226125512359:ios:131e31be576fd2eecea582',
    messagingSenderId: '226125512359',
    projectId: 'mixologist-76592',
    storageBucket: 'mixologist-76592.firebasestorage.app',
    iosBundleId: 'com.example.mixologistFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOsNH_IUFfMY7PC_K2B7YE2Vzj-WkGZwc',
    appId: '1:226125512359:web:f6db873e4033321acea582',
    messagingSenderId: '226125512359',
    projectId: 'mixologist-76592',
    authDomain: 'mixologist-76592.firebaseapp.com',
    storageBucket: 'mixologist-76592.firebasestorage.app',
    measurementId: 'G-H8P24LFDEE',
  );
}
