name: PR Tests

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        
    - name: Run Python tests
      run: |
        cd tests
        python -m pytest test_openai_service.py -v

  flutter-tests:
    name: Flutter Tests  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.1'
        channel: 'stable'
        
    - name: Install Flutter dependencies
      working-directory: ./flutter_app
      run: flutter pub get
      
    - name: Run Flutter tests
      working-directory: ./flutter_app
      run: flutter test

  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [python-tests, flutter-tests]
    if: always()
    
    steps:
    - name: Check test results
      run: |
        if [[ "${{ needs.python-tests.result }}" == "success" && "${{ needs.flutter-tests.result }}" == "success" ]]; then
          echo "✅ All tests passed!"
          exit 0
        else
          echo "❌ Some tests failed:"
          echo "Python tests: ${{ needs.python-tests.result }}"
          echo "Flutter tests: ${{ needs.flutter-tests.result }}"
          exit 1
        fi